config/routes.rb
# == Route Map
#

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  root "application#index"
  devise_for :users

  resources :feeds
  resources :directories
  resources :articles, only: [:index]

  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_article.html.erb
<div class="card rss-article" data-list-target="article" data-article-id="<%= article.id %>">
  <div class="card-header">
    <%= feed_icon article.feed, "16" %>&nbsp;
    <span class="font-weight-lighter"><%= article.feed.title %></span>&nbsp;
    <%= article.title %>
    <%= fa_icon "star", class: "float-right" %>
  </div>
  <div class="card-body">
    <h3><a href="<%= article.url %>" target="_blank" rel="noopener noreferrer"><%= article.title %>&nbsp;<%= fa_icon "external-link-alt" %></a></h3>
    <% article_tags = @tags.select { |t| t.article_id == article.id } %>
    <p><%= article.author ? "By: #{article.author} " : "" %><%= article_tags.length > 0 ? "(#{article_tags.map(&:title).join(", ")})" : "" %></p>
    <div class="content">
      <%= mark_safe article.description %>
    </div>
  </div>
  <div class="card-footer font-weight-lighter">
    <label for="read-<%= article.id %>">Read</label>&nbsp;
    <input
      name="read-<%= article.id %>"
      type="checkbox"/>&nbsp;&nbsp;
    <span title="<%= article.pub_date.to_s %>"><%= time_ago_in_words article.pub_date %> ago</span>
    <div class="btn-group float-right" role="group">
      <button class="btn btn-secondary btn-xs"><%= fa_icon "angle-double-up" %></button>
      <button class="btn btn-secondary btn-xs"><%= fa_icon "angle-up" %></button>
      <button class="btn btn-secondary btn-xs"><%= fa_icon "angle-down" %></button>
      <button class="btn btn-secondary btn-xs"><%= fa_icon "angle-double-down" %></button>
    </div>
  </div>
</div>

app/views/shared/_articles.html.erb
<%= turbo_frame_tag "details", loading: "lazy" do %>
  <% if @articles.count > 0 %>
    <% @articles.each do |article| %>
      <%= render 'shared/article', article: article %>
    <% end %>
  <% else %>
  <%= render 'shared/empty', title: "No articles found" %>
  <% end %>
<% end %>

app/views/shared/_empty.html.erb
<div class="p-5 mb-4 bg-dark rounded-3">
  <div class="container">
    <h1 class="display-4 text-center"><%= title %></h1>
    <h1 class="display-4 text-center"><%= fa_icon "coffee" %></h1>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark" data-turbo-permanent="true">
  <div class="col-lg-3" style="margin-left: 0.5rem;">
    <div class="btn-group btn-group-sm">
      <%= link_to new_feed_path, class: "btn btn-sm btn-primary", title: "Subscribe" do %>
        <%= fa_icon "rss" %>
      <% end %>
      <%= link_to new_directory_path, class: "btn btn-sm btn-secondary", title: "New Directory" do %>
        <%= fa_icon "plus" %>
      <% end %>
      <button class="btn btn-sm btn-secondary" title="Import OPML"><%= fa_icon "upload" %></button>
      <button class="btn btn-sm btn-secondary" title="Export OPML"><%= fa_icon "file-code" %></button>
      <% if notice %><span class="badge secondary"><%= notice %></span><% end %>
    </div>
  </div>
  <div class="col-lg-9">
    <div class="btn-group btn-group-sm">
      <button class="btn btn-sm btn-secondary" title="Refresh"><%= fa_icon "redo" %></button>
      <button class="btn btn-sm btn-secondary" title="Refresh all"><%= fa_icon "sync-alt" %></button>
    </div>
    <div class="btn-group btn-group-sm">
      <button class="btn btn-sm btn-secondary" title="Mark older than 30 days"><%= fa_icon "check" %></button>
      <button class="btn btn-sm btn-secondary" title="Mark older than 7 days"><%= fas_icon "check-double" %></button>
      <button class="btn btn-sm btn-secondary" title="Mark all as read"><%= fa_icon "tasks" %></button>
    </div>
    <div class="btn-group btn-group-sm btn-group-toggle">
      <button class="btn btn-sm btn-secondary" title="Unread"><%= fa_icon "eye-slash" %></button>
      <button class="btn btn-sm btn-secondary" title="All"><%= fa_icon "eye" %></button>
    </div>
    <div class="btn-group btn-group-sm">
      <button class="btn btn-sm btn-secondary" title="Settings"><%= fa_icon "sliders-h" %></button>
      <button class="btn btn-sm btn-secondary" title="Admin settings"><%= fa_icon "users-cog" %></button>
      <button class="btn btn-sm btn-secondary" title="Keyboard shortcuts" data-bs-toggle="modal" data-bs-target="#keyboardHelp"><%= fa_icon "keyboard" %></button>
      <button class="btn btm-sm btn-secondary" title="Logout" data-action="list#logout"><%= fas_icon "sign-out-alt" %></button>
    </div>
    <form style="display: inline-block; float: right; margin-right: 1rem;" data-action="list#submitSearch">
      <label class="visually-hidden" for="search-box">Search</label>
      <div class="input-group">
        <div class="input-group-text"><%= fas_icon "search" %></div>
        <input type="text" class="form-control form-control-dark"
          id="search-box" data-list-target="inputSearch" placeholder="Search"
          <% if params[:q].present? %>
          value="<%= params[:q] %>"
          <% end %>
          />
      </div>
    </form>
  </div>
</nav>

app/views/shared/_tree.html.erb
<%= link_to feeds_path do%>
  <%= fa_icon "inbox" %>&nbsp;All
<% end %>
<% tree = load_tree(current_user.id) %>
<%= render 'shared/tree_directory', tree: tree, totals: tree.totals %>

app/views/shared/_tree_directory.html.erb
<% if tree.item.title != 'Root' %>
  <li>
    <%= link_to directory_path(tree.item), data: { "list-target": "directory", directory_id: tree.item.id, directory_title: tree.item.title } do %>
      <%= fa_icon "folder" %>&nbsp;<%= tree.item.title %>
    <% end %>
  </li>
<% end %>
<% if tree.children.size > 0 %>
  <ul class="directory">
    <% tree.children.each do |dir| %>
      <%= render 'shared/tree_directory', tree: dir, totals: totals %>
    <% end %>
  </ul>
<% end %>
<% if tree.feeds.size > 0 %>
  <ul class="feed-list">
    <% tree.feeds.each do |feed| %>
      <li>
        <% unread_count = totals[feed.id] %>
        <%= link_to feed_path(feed), data: { "list-target": 'feed', feed_id: feed.id, feed_title: feed.title } do %>
        <%= feed_icon feed, "16" %>
        &nbsp;<%= feed.title %>&nbsp;<span class="badge rounded-pill <%= if unread_count&.zero? then 'bg-success' else 'bg-secondary' end %>"><%= unread_count %></span><% end %>
        <%= link_to edit_feed_path(feed), class: "float-right edit" do %><%= fa_icon "wrench" %><% end %>
      </li>
    <% end %>
  </ul>
<% end %>